### ISSUE TITLE
can you solve this error please ?

### ISSUE THREAD

**Issue by yaswanth-iitkgp** [LorrinWWW/Pyramid#8]
reading pretrained wv from /model1/wv/pre_trained_wv/glove.6B.100d.txt
19995it [00:00, 35172.53it/s]
Traceback (most recent call last):
  File "model1/Pyramid/train_ner.py", line 168, in <module>
    model.token_embedding.load_pretrained(args.pretrained_wv, freeze=args.freeze_wv)
  File "model1/Pyramid/layers/encodings/embeddings.py", line 123, in load_pretrained
    embedding_matrix[idx] = vector
IndexError: index 20000 is out of bounds for dimension 0 with size 20000

**Comment by yaswanth-iitkgp** [comment]
can you please reply ? @LorrinWWW

**Comment by Arios-29** [comment]
just seting it to the size of the pretrained word embbedings works fine. 
Howerver, there are so many bugs in the code.
the author didnt detail any configuration information and i sugggest u not use this code and i dont think the paper is valuable bc of this terrible code.
